### PR TITLE
Use trimws from backports

### PR DESCRIPTION
**Pull request by shabbybanks**
To address https://github.com/rich-iannone/pointblank/issues/9 , I am replacing `trimws` with `backports::trimws` where needed. I put each edit in a separate commit to simplify cherry picking (but also because I cannot git clone on my work computer.) Your mileage may vary on whether you want to use `backports::trimws` in the `README.md` for example.

### CODE REVIEW

**Comment by nutterb** [comment]
I won't be committing this at this time, as `backports` does not export `trimws`.

**Comment by shabbybanks** [comment]
oops., my bad.

**Comment by nutterb** [comment]
No worries.  It seemed like a good idea until Travis failed. If not for that, I wouldn't have noticed anything was wrong.

**Comment by shabbybanks** [comment]
It seems that `trimws` is not used in the code anywhere except in the documentation, vignette and `README.rmd`, where the fully quoted version `backports::trimws` would suffice. So removing the `importFrom` would suffice for a build, I think.

**Pull request closed without merging**
